# Generated by Django 2.1a1 on 2018-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assertions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pref', models.CharField(max_length=250)),
                ('assertion_type', models.IntegerField()),
                ('parameters', models.TextField()),
            ],
            options={
                'db_table': 'assertions',
            },
        ),
        migrations.CreateModel(
            name='AssertionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pref', models.CharField(max_length=250)),
                ('assertion_type', models.CharField(max_length=250)),
                ('parameter', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'assertions_types',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('location', models.TextField()),
                ('hometown', models.TextField()),
                ('about', models.TextField()),
                ('numfriends', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
