# Generated by Django 2.0.2 on 2018-03-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='TrainingEvents',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='TrainingLikes',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='TrainingPosts',
        ),
    ]
